title: 'ğŸ–‹ï¸ Shell Pen'
description: 'Generate Shell Script Source Code'

twitter_username: rebeccca_taylor
github_username: beccasaurus

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ['_pages']

remote_theme: 'mmistakes/minimal-mistakes@4.22.0'
minimal_mistakes_skin: air

atom_feed:
  hide: true